### PR TITLE
Big chat upgrade

### PR DESCRIPTION
**Pull request by Ahmadkhan02**
/claim https://github.com/smallcloudai/refact-vscode/issues/28

new pull request as to not make any conflicts
all pendings of #33 covered
moved chat to the existing sidebar

### CODE REVIEW

**Comment by olegklimov** [comment]
Can you please 🙏  make less changes in:

747 changes package.json
858 changes src/extension.ts
361 changes src/highlight.ts
1,141 changes src/sidebar.ts
38 changes src/storeVersions.ts

so someone can actually work and understand the changes

**Comment by Ahmadkhan02** [comment]
> Can you please 🙏 make less changes in:
> 
> 747 changes package.json 858 changes src/extension.ts 361 changes src/highlight.ts 1,141 changes src/sidebar.ts 38 changes src/storeVersions.ts
> 
> so someone can actually work and understand the changes

tried to fix it!! hope Its fine now

**Comment by Ahmadkhan02** [comment]
@olegklimov do you need me to re-commit another file?

**Comment by Ahmadkhan02** [comment]
@olegklimov please review this and/or tell me more changes if required as I will be busy with some examinations in the upcoming week

**Comment by olegklimov** [comment]
Hi @Ahmadkhan02 sorry to keep you waiting, it was a busy week!

**Comment by olegklimov** [comment]
Yes, it's much better with unnecessary changes! I'll take a look within a day.

**Comment by Ahmadkhan02** [comment]
> Yes, it's much better with unnecessary changes! I'll take a look within a day.

I have shifted chat to the main sidebar itself. As I had tried doing a new one for chat before, I find making a new one and maintaining login etc on that more of a hassle. Keep this in mind while reviewing.

**Comment by Ahmadkhan02** [comment]
@olegklimov have you started because otherwise I was thinking of some code structure improvements like making both chatTab and chatHistoryProvider singleton

**Comment by olegklimov** [comment]
I have time today to take a look. No opinion yet, let me look.

**Comment by olegklimov** [comment]
I think it's fantastic work! 

I found a couple of bugs for sure, but it's minor things left.

https://github.com/smallcloudai/refact-vscode/assets/18546213/3c35ac84-095c-4719-a22e-cd34591c7b07

Enter doesn't work when editing, editing leaves funny traces, sometimes "stop generating" doesn't want to go away (end of the video, easy to reproduce by hitting F1)

**Comment by Ahmadkhan02** [comment]
@olegklimov 
> Enter doesn't work when editing, editing leaves funny traces, sometimes "stop generating" doesn't want to go away (end of the video, easy to reproduce by hitting F1)

Made these changes, were quite easy. I had forgotten about adding enter key functionality on retry input. Also made retry unresponsive while stop-button is visible.

**Comment by Ahmadkhan02** [comment]
@olegklimov do tell if any other change is required.

**Comment by olegklimov** [comment]
> other change is required
I'll merge it into `oleg_checking_lsp` branch, hopefully tomorrow.

**Pull request closed without merging**
