### PR TITLE
Chat Overhaul Implementation

### LINKED ISSUE #28: [bounty] Chat overhaul
The current chat is this:

image

The good about it:

* Opens on shortcut (Alt+C)
* Any selected code automatically gets copied into ''' section
* It receives the answer with streaming, autoscroll, markdown
* Code blocks have buttons: `diff`, `new file`, `copy`
* The `retry` button allows to go back and change the question

image

The bad about it:

* Autoscroll is too invasive: if the answer is still streaming, it will not allow to copy-paste an already useful part of the answer.
* `diff`, `new file`, `copy` are not available until streaming is finished.
* It's better for `retry` button to edit question in place (similar to OpenAI chat UI).
* Code blocks have no syntax highlight.
* Style could be better.

Epic change needed: instead of tabs, use sidebar. Make a new one, to avoid conflicting with the existing sidebar.

* History becomes a button that opens a list previous conversations (similar to Sourcegraph UI)
* After switching to a previous conversation, the user should be able to continue it, or use `retry`
* Chat history should survive IDE restart, stored in globalState or similar

image
Picture: history in sourcegraph UI

A good solution is:
* Small code, compared to the existing one, or at least not much more
* Clear what's going on, when looking at any given screenful of code

### PR DESCRIPTION
**Pull request by aazam-gh**
Fix #28

### CODE REVIEW

**Comment by olegklimov** [comment]
Hey @aazam-gh , another user Ahmadkhan02 is much closer to the goal.

**Comment by aazam-gh** [comment]
Hello @olegklimov yes I can see that. Should I withdraw my pr?

**Comment by olegklimov** [comment]
> Should I withdraw my pr

I think it's best to wait if Ahmadkhan02 will be able to finish and merge his solution

**Comment by aazam-gh** [comment]
> > Should I withdraw my pr
> 
> I think it's best to wait if Ahmadkhan02 will be able to finish and merge his solution
> 

I see but you still want the chat to be implemented in a secondary sidebar correct?

**Comment by olegklimov** [comment]
No, the final version should have 1 sidebar, it was 2 for simplicity.

**Comment by aazam-gh** [comment]
> No, the final version should have 1 sidebar, it was 2 for simplicity.

Would the single sidebar change be required soon?

**Pull request closed without merging**
